### ISSUE TITLE
Custom css properties inside svg of custom iconset

### ISSUE THREAD

**Issue by mikaelharsjo** [PolymerElements/iron-iconset-svg#19]
Is this supported?

```html
<iron-iconset-svg name="custom-icons" size="80">
  <svg>
    <style>
      .icon {
        fill: var(--paper-red-500);
     }
   </style>
  </svg>
</iron-iconset-svg>
```
It didn't work for me but it may be something with my setup.

**Comment by notwaldorf** [comment]
@mikaelharsjo I think this does not work. It's a little bit weird with how the `<svg>` element works, and where this stylesheet actually lives (which isn't where it's eventually getting used). I think your best bet is to not use custom properties inside the `<svg>` document, sorry :(

@sorvell in case he has any good ideas for this

**Comment by mikaelharsjo** [comment]
No worries, that's what I thought
