### ISSUE TITLE
The element seems to generate some height

### ISSUE THREAD

**Issue by akc42** [PolymerElements/iron-iconset-svg#27]
I was expecting this element not to display, as it just defines an icon to be used elsewhere.

I created one with a small element I wanted to include as an icon (a calendar) and started by putting just after the body tag.  But then my <paper-header> element didn't start at the top of the page

I was able to make it disappear by adding the attribute style="display:none;"

**Comment by notwaldorf** [comment]
Hmmm, I'm not sure what you mean -- I can't see it in the demo, so I don't think we're thinking about the same thing :)
Do you have a jsbin or a code snippet to repro this? Thanks!

**Comment by akc42** [comment]
I can't find a way to get jsbin to include the latest polymer libraries, but the html page there is a direct copy of a my index.html file

https://jsbin.com/zurabo/edit?html,output

The elements contained within were obtained by bower installing the following bower.json file

```
{
  "name": "polymer-trial",
  "version": "0.0.0",
  "authors": [
    "Alan Chandler <alan@chandlerfamily.org.uk>"
  ],
  "description": "Testbed for trying front page polymer layouts",
  "main": "index.html",
  "moduleType": [],
  "keywords": [
    "trial"
  ],
  "license": "MIT",
  "homepage": "",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "polymer": "Polymer/polymer#^1.1.0",
    "iron-elements": "PolymerElements/iron-elements#~1.0.4",
    "paper-elements": "PolymerElements/paper-elements#~1.0.5",
    "neon-elements": "PolymerElements/neon-elements#~1.0.0"
  }
}
```

When I serve up the index page with polyserve and look at it with chrome (46 - under Debian Linux) I get a gap at the top of the screen until I add a style="display:none" to the iron-iconset-svg element .

**Comment by notwaldorf** [comment]
I've updated this to use polygit: https://jsbin.com/zuvumi/edit?html,output and I see what you mean. On it! :)
