### ISSUE TITLE
Feature: add a neutral-mood icon

### ISSUE THREAD

**Issue by fabiomolinar** [PolymerElements/iron-iconset-svg#63]
### Description
It already currently exists two mood emoticons in the set. One for "positive" mood, another for "negative" mood, "mood" and "mood-bad" respectively. I believe it would be a good idea to add a "neutral" mood emoticon to this set. That way we can use this three emoticons in forms where users can rate/evaluate/assess something's grade/satisfaction/usefulness. 

### Expected outcome
An additional svg description of a neutral mood emoticon to the set of icons.

### Actual outcome
I am currently using the "face" icon for the neutral emoticon. But it doesn't match so good with the design of the "mood" and "mood-bad" icons.

### Example of neutral mood faces
[grading emoticons example](http://t2.ftcdn.net/jpg/00/44/22/53/400_F_44225314_r8lRSJlgF2E1B6dnvvXtwjD6euWWJc50.jpg)

**Comment by stramel** [comment]
This isn't the place for icon requests. This is just a component for defining a library of svg icons. `iron-icons` is where they actually define the icon sets. However, AFAIK, they just define the material icons. You would have better luck trying to get it in over there or just rolling your own icon set.

**Comment by notwaldorf** [comment]
Yup, the icons are pulled in from https://github.com/google/material-design-icons using a script, so there's nothing we can do (other than re-run the script when there's new icons)
