### ISSUE TITLE
custom icons not working in polymer 2

### ISSUE THREAD

**Issue by esd100** [PolymerElements/iron-iconset-svg#69]
### Description
Polymer 2 migration is so frustrating! My custom icons were working in polymer 1 and now they are not working in polymer 2

```
          <paper-icon-item name="home">
            <iron-icon icon="appIcons:home" slot="item-icon"></iron-icon><a href="/home" link>Home</a>
          </paper-icon-item>

```

and

```
            <paper-icon-button icon="appIcons:menu" drawer-toggle></paper-icon-button>

```

**Comment by esd100** [comment]
Anybody working on Polymer able to help with this issue?

**Comment by TrentBrown** [comment]
Oh, man. I thought I'd done something wrong, but it looks like it's not just me.
Moved to 2.0.0 components from one-oh-something, and my icons disappeared.
Been spinning my wheels for several hours already.
I feel better knowing that I'm not suffering alone, but I want the pain to go away.
No workaround for this?

**Comment by btelles** [comment]
I'm seeing similar issues on an existing app that I upgraded to Polymer 2. I've tried to reduce the problem to minimum steps to reproduce, but I can't seem to find a happy medium. @esd100 and @TrentBrown , the code snippet above doesn't give us the whole story. Any chance either of you can narrow the problem down a bit so the Polymer team can try and help out?

**Comment by esd100** [comment]
@btelles Thanks so much for figuring this out! That fixed it!

**Comment by tanin47** [comment]
Upgrading `iron-meta` explicitly solves the issue with non-showing icons for me as well.

**Comment by vishnuprasadps** [comment]
@btelles Thanks.. Its solved my problem.. ! @esd100 Thanks for the helpful question...

**Comment by Piot** [comment]
This fixed the missing icon for me as well. Thanks!

**Comment by mastercodekw** [comment]
This fixed the icon-disappearing issue for me as well.
The issue should be closed.

**Comment by nuriaruiz** [comment]
In my case, I installed iron-iconset-svg 2.1.1 last week, and it seems that the installation installed the wrong iron-meta because I could not see the icon until I explicitly added iron-meta 2.0.0  to my dependencies following your instructions
