### ISSUE TITLE
Where can I find the API docs?

### ISSUE THREAD

**Issue by tomalec** [PolymerElements/iron-iconset-svg#78]
### Description

Github page links to https://www.webcomponents.org/element/PolymerElements/iron-iconset-svg

### Expected outcome
I would like to see API  described, like attribute I can set, their default values and behavior.

### Actual outcome
There is no such thing.

### Live Demo

https://www.webcomponents.org/element/PolymerElements/iron-iconset-svg?view=demo:demo/index.html

### Steps to reproduce

1. Open https://github.com/PolymerElements/iron-iconset-svg,
2. Open https://www.webcomponents.org/element/PolymerElements/iron-iconset-svg

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by notwaldorf** [comment]
Yup, the docs are there. If you look on the left hand side menu and click `iron-iconset-svg` under "Elements", you'll get to this: https://www.webcomponents.org/element/PolymerElements/iron-iconset-svg/elements/iron-iconset-svg
