### ISSUE TITLE
Icons rendered in RTL with Shadom DOM transform around the wrong origin

### ISSUE THREAD

**Issue by dlockhart** [PolymerElements/iron-iconset-svg#80]
### Description
When `<iron-iconset-svg>` is used in a page with right-to-left (`dir="rtl"`) direction, with an icon that mirrors itself, on a browser which supports native Shadow DOM, the icon is mirrored from the incorrect origin. This results in it being positioned outside its container.

Right-to-left (incorrect origin)
![iconset-rtl](https://user-images.githubusercontent.com/5491151/35463742-2fa4106a-02c0-11e8-9155-bd90c81ddda3.png)

Left-to-right (correct origin)
![iconset-ltr](https://user-images.githubusercontent.com/5491151/35463759-41676c52-02c0-11e8-9810-1493d1a96b90.png)

### Expected outcome

The icon should mirror along its center horizontal and vertical axes.

### Actual outcome

The icon mirrors

### Live Demo

Make sure you're using Chrome:
https://jsbin.com/jotojuzuru/edit?html,output

### Steps to reproduce

1. Create an `<iron-iconset-svg>` with `rtl-mirror="true"`
2. Inside, put an icon that requires mirroring using the `mirror-in-rtl="true"` attribute
3. Use that icon inside a page with right-to-left direction (`dir="rtl"` on the `<body>` or `<html>` elements)
4. Visit the page in a browser that supports native Shadow DOM
5. Notice that the icon is mirrored along the incorrect origin
6. Switch to shady DOM and notice the origin is now correct

Sample code:

```
<link rel="import" href="../iron-icon/iron-icon.html">
<link rel="import" href="../iron-iconset-svg/iron-iconset-svg.html"/>
<iron-iconset-svg name="example" size="18" rtl-mirroring="true">
  <svg>
    <defs>
      <g id="chevron-right" mirror-in-rtl="true">
        <path d="M5.49 15.61a1.5 1.5 0 0 1-.1-2.12L9.47 9 5.39 4.51a1.5 1.5 0 1 1 2.22-2.02L12.62 8A1.474 1.474 0 0 1 13 9a1.524 1.524 0 0 1-.38 1l-5.01 5.51a1.5 1.5 0 0 1-2.12.1z"/>
      </g>
    </defs>
  </svg>
</iron-iconset-svg>
<div style="display:inline-block;border:1px solid red;">
    <iron-icon icon="example:chevron-right"></iron-icon>
</div>
```

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

### Possible Fix

Add `transform-origin: center;` to the [CSS which is performing the transform](https://github.com/PolymerElements/iron-iconset-svg/blob/master/iron-iconset-svg.html#L249).

**Comment by bicknellr** [comment]
I think this is actually a Chrome bug. [This rule in the UA stylesheet for SVG](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/css/svg.css?l=82&rcl=871421fc01829cd9078320f0974a361fec2f4622) doesn't match `<svg>` elements which are the children of ShadowRoots: it should also have `:host(html|*) > svg`.

**Comment by dlockhart** [comment]
Isn't @robdodson playing around in the Chromium code these days? `:focus-visible` can wait... ;)

**Comment by bicknellr** [comment]
Filed as https://crbug.com/808228.
